<template><div><h1 id="类型体操" tabindex="-1"><a class="header-anchor" href="#类型体操" aria-hidden="true">#</a> 类型体操</h1>
<h2 id="组件类型丢失问题" tabindex="-1"><a class="header-anchor" href="#组件类型丢失问题" aria-hidden="true">#</a> 组件类型丢失问题</h2>
<p>全局引入类型（vite-env.d.ts）</p>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token comment">/// &lt;reference types="ant-design-vue/typeings/global.d.ts"></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h2 id="获取组件类型" tabindex="-1"><a class="header-anchor" href="#获取组件类型" aria-hidden="true">#</a> 获取组件类型</h2>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token keyword">const</span> formRef <span class="token operator">=</span> <span class="token generic-function"><span class="token function">ref</span><span class="token generic class-name"><span class="token operator">&lt;</span>InstanceType<span class="token operator">&lt;</span><span class="token keyword">typeof</span> ElForm<span class="token operator">>></span></span></span><span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token keyword">export</span> <span class="token keyword">function</span> useCompRef<span class="token operator">&lt;</span><span class="token constant">T</span> <span class="token keyword">extends</span> <span class="token class-name"><span class="token keyword">abstract</span></span> <span class="token keyword">new</span> <span class="token punctuation">(</span><span class="token operator">...</span>args<span class="token operator">:</span><span class="token builtin">any</span><span class="token punctuation">)</span><span class="token operator">=></span><span class="token builtin">any</span><span class="token operator">></span><span class="token punctuation">(</span>_comp<span class="token operator">:</span><span class="token constant">T</span><span class="token punctuation">)</span><span class="token punctuation">{</span>
    <span class="token keyword">return</span> <span class="token generic-function"><span class="token function">ref</span><span class="token generic class-name"><span class="token operator">&lt;</span>InstanceType<span class="token operator">&lt;</span><span class="token constant">T</span><span class="token operator">>></span></span></span><span class="token punctuation">(</span><span class="token punctuation">)</span>
<span class="token punctuation">}</span>                          
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="infer" tabindex="-1"><a class="header-anchor" href="#infer" aria-hidden="true">#</a> infer</h2>
<p>推断promise的返回值</p>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token keyword">type</span> <span class="token class-name">PromiseType<span class="token operator">&lt;</span><span class="token constant">T</span><span class="token operator">></span></span> <span class="token operator">=</span> <span class="token constant">T</span> <span class="token keyword">extends</span> <span class="token class-name"><span class="token builtin">Promise</span></span><span class="token punctuation">(</span><span class="token keyword">infer</span> <span class="token constant">K</span><span class="token punctuation">)</span> <span class="token operator">?</span> PromiseType<span class="token operator">&lt;</span><span class="token constant">K</span><span class="token operator">></span> <span class="token operator">:</span> <span class="token constant">T</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h2 id="字段-函数推导" tabindex="-1"><a class="header-anchor" href="#字段-函数推导" aria-hidden="true">#</a> 字段-函数推导</h2>
<p>由于对象键可能是<code v-pre>symbol</code>因此<code v-pre>${keyof T}Changed</code>会报错这里需要用<code v-pre>string&amp;</code>约束</p>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token keyword">type</span> <span class="token class-name">Watcher<span class="token operator">&lt;</span><span class="token constant">T</span><span class="token operator">></span></span> <span class="token operator">=</span> <span class="token punctuation">{</span>
    <span class="token generic-function"><span class="token function">on</span><span class="token generic class-name"><span class="token operator">&lt;</span><span class="token constant">K</span> <span class="token keyword">extends</span> <span class="token builtin">string</span> <span class="token operator">&amp;</span> <span class="token keyword">keyof</span> <span class="token constant">T</span><span class="token operator">></span></span></span><span class="token punctuation">(</span>eventName<span class="token operator">:</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span><span class="token constant">K</span><span class="token interpolation-punctuation punctuation">}</span></span><span class="token string">Changed</span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token operator">:</span><span class="token keyword">void</span>
    <span class="token function-variable function">callback</span><span class="token operator">:</span><span class="token punctuation">(</span>oldValue<span class="token operator">:</span><span class="token constant">T</span><span class="token punctuation">[</span><span class="token constant">K</span><span class="token punctuation">]</span><span class="token punctuation">,</span>newValue<span class="token operator">:</span><span class="token constant">T</span><span class="token punctuation">[</span><span class="token constant">K</span><span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token operator">=></span><span class="token keyword">void</span>
<span class="token punctuation">}</span>
<span class="token keyword">const</span> person <span class="token operator">=</span> <span class="token function">watch</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
    firstName<span class="token operator">:</span><span class="token string">'JERY'</span> <span class="token punctuation">,</span>
    lastName<span class="token operator">:</span><span class="token string">'AA'</span><span class="token punctuation">,</span>
    age<span class="token operator">:</span><span class="token number">25</span>
<span class="token punctuation">}</span><span class="token punctuation">)</span>
per
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="将数组每一项作为对象的键" tabindex="-1"><a class="header-anchor" href="#将数组每一项作为对象的键" aria-hidden="true">#</a> 将数组每一项作为对象的键</h2>
<div class="language-typescript line-numbers-mode" data-ext="ts"><pre v-pre class="language-typescript"><code><span class="token keyword">const</span> arr0 <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">,</span> <span class="token number">99</span><span class="token punctuation">,</span> <span class="token string">'foo'</span><span class="token punctuation">,</span> <span class="token string">'bar'</span><span class="token punctuation">]</span> <span class="token keyword">as</span> <span class="token keyword">const</span><span class="token punctuation">;</span>

<span class="token keyword">type</span> <span class="token class-name">Test<span class="token operator">&lt;</span><span class="token constant">T</span> <span class="token keyword">extends</span> <span class="token keyword">readonly</span> <span class="token builtin">unknown</span><span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">,</span> <span class="token constant">U</span> <span class="token operator">=</span> <span class="token punctuation">{</span>index<span class="token operator">:</span><span class="token builtin">number</span><span class="token punctuation">,</span>value<span class="token operator">:</span><span class="token builtin">number</span><span class="token punctuation">,</span>checked<span class="token operator">:</span><span class="token builtin">boolean</span><span class="token punctuation">}</span><span class="token operator">></span></span> <span class="token operator">=</span> <span class="token punctuation">{</span> <span class="token punctuation">[</span><span class="token constant">P</span> <span class="token keyword">in</span> <span class="token constant">T</span><span class="token punctuation">[</span><span class="token builtin">number</span><span class="token punctuation">]</span> <span class="token operator">&amp;</span> PropertyKey<span class="token punctuation">]</span><span class="token operator">?</span><span class="token operator">:</span> <span class="token constant">U</span> <span class="token punctuation">}</span><span class="token punctuation">;</span>

<span class="token keyword">const</span> test1<span class="token operator">:</span> Test<span class="token operator">&lt;</span><span class="token keyword">typeof</span> arr0<span class="token operator">></span> <span class="token operator">=</span> <span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">;</span>

test1<span class="token punctuation">[</span><span class="token number">1</span><span class="token punctuation">]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><CommentService/></div></template>


