<template><div><h1 id="css相关问题" tabindex="-1"><a class="header-anchor" href="#css相关问题" aria-hidden="true">#</a> CSS相关问题</h1>
<h2 id="_1-多行文本溢出" tabindex="-1"><a class="header-anchor" href="#_1-多行文本溢出" aria-hidden="true">#</a> 1.多行文本溢出</h2>
<p>方式①</p>
<div class="language-html line-numbers-mode" data-ext="html"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>head</span><span class="token punctuation">></span></span>
	<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>style</span><span class="token punctuation">></span></span><span class="token style"><span class="token language-css">
        <span class="token selector">.container</span> <span class="token punctuation">{</span>
            <span class="token property">width</span><span class="token punctuation">:</span> 200px<span class="token punctuation">;</span>
            <span class="token property">height</span><span class="token punctuation">:</span> 100px<span class="token punctuation">;</span>
            <span class="token property">background-color</span><span class="token punctuation">:</span> #efefef<span class="token punctuation">;</span>
            <span class="token property">display</span><span class="token punctuation">:</span> -webkit-box<span class="token punctuation">;</span>
            <span class="token property">overflow</span><span class="token punctuation">:</span> hidden<span class="token punctuation">;</span>
            <span class="token property">-webkit-box-orient</span><span class="token punctuation">:</span> vertical<span class="token punctuation">;</span>
            <span class="token property">-webkit-line-clamp</span><span class="token punctuation">:</span> 5 <span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
    </span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>style</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>head</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>body</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>div</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>container<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
        <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>div</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>p<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
            From the age groups, we can see that the largest group of citizens is the group in the age between 20-29. People in this period have had their own career.In this society of ever-quickening pace, working with copmputer has become a fashion. Furthermore, they also use it to entertain themselves and find the right person. The group secondary to this group is in the age between 10-19. In this period, middle school students mostly use computer to play games and chat with others, people in college use it both to entertain themselves and learn what they need to learn. And amount of people in this period fall in love so they spend much on chatting with their beloved people. Top3 is in the age between 30-39. In this period, middle aged people have lost part of interest of playing games and the need of l
        <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>div</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>div</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>body</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>②方式二</p>
<div class="language-html line-numbers-mode" data-ext="html"><pre v-pre class="language-html"><code><span class="token doctype"><span class="token punctuation">&lt;!</span><span class="token doctype-tag">DOCTYPE</span> <span class="token name">html</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>html</span> <span class="token attr-name">lang</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>en<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>head</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>meta</span> <span class="token attr-name">charset</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>UTF-8<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>meta</span> <span class="token attr-name">name</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>viewport<span class="token punctuation">"</span></span> <span class="token attr-name">content</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>width=device-width, initial-scale=1.0<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>title</span><span class="token punctuation">></span></span>Document<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>title</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>style</span><span class="token punctuation">></span></span><span class="token style"><span class="token language-css">
        <span class="token selector">.text-container</span> <span class="token punctuation">{</span>
            <span class="token property">width</span><span class="token punctuation">:</span> 200px<span class="token punctuation">;</span>
            <span class="token property">height</span><span class="token punctuation">:</span> 100px<span class="token punctuation">;</span>
            <span class="token property">background-color</span><span class="token punctuation">:</span> #efefef<span class="token punctuation">;</span>
            <span class="token property">overflow</span><span class="token punctuation">:</span> hidden<span class="token punctuation">;</span>
            <span class="token property">padding</span><span class="token punctuation">:</span>0 10px<span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
        <span class="token selector">.text-container::before</span><span class="token punctuation">{</span>
            <span class="token property">content</span><span class="token punctuation">:</span> <span class="token string">''</span><span class="token punctuation">;</span>
            <span class="token property">display</span><span class="token punctuation">:</span> block<span class="token punctuation">;</span>
            <span class="token property">height</span><span class="token punctuation">:</span> 80px<span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
        <span class="token selector">.p</span><span class="token punctuation">{</span>
            <span class="token property">margin-top</span><span class="token punctuation">:</span> -80px<span class="token punctuation">;</span>  
        <span class="token punctuation">}</span>
        <span class="token selector">.ellipsis</span><span class="token punctuation">{</span>
            <span class="token property">float</span><span class="token punctuation">:</span> right<span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
    </span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>style</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>head</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>body</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>div</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>container<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
        <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>div</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>text-container<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
            <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>div</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>ellipsis<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
                ...
            <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>div</span><span class="token punctuation">></span></span>
            <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>div</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>p<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
                From the age groups, we can see that the largest group of citizens is the group in the age between 20-29. People in this period have had their own career.In this society of ever-quickening pace, working with copmputer has become a fashion. Furthermore, they also use it to entertain themselves and find the right person. The group secondary to this group is in the age between 10-19. In this period, middle school students mostly use computer to play games and chat with others, people in college use it both to entertain themselves and learn what they need to learn. And amount of people in this period fall in love so they spend much on chatting with their beloved people. Top3 is in the age between 30-39. In this period, middle aged people have lost part of interest of playing games and the need of
            <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>div</span><span class="token punctuation">></span></span>
        <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>div</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>div</span><span class="token punctuation">></span></span>
    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>script</span><span class="token punctuation">></span></span><span class="token script"><span class="token language-javascript">
        <span class="token keyword">const</span> p <span class="token operator">=</span> document<span class="token punctuation">.</span><span class="token function">querySelector</span><span class="token punctuation">(</span><span class="token string">'.p'</span><span class="token punctuation">)</span>
        <span class="token keyword">const</span> ellipsis <span class="token operator">=</span> document<span class="token punctuation">.</span><span class="token function">querySelector</span><span class="token punctuation">(</span><span class="token string">'.ellipsis'</span><span class="token punctuation">)</span>
        <span class="token keyword">const</span> textContainer <span class="token operator">=</span> document<span class="token punctuation">.</span><span class="token function">querySelector</span><span class="token punctuation">(</span><span class="token string">'.text-container'</span><span class="token punctuation">)</span>
        <span class="token keyword">const</span> <span class="token punctuation">{</span><span class="token literal-property property">height</span><span class="token operator">:</span>pHeight<span class="token punctuation">}</span> <span class="token operator">=</span> p<span class="token punctuation">.</span><span class="token function">getBoundingClientRect</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
        <span class="token keyword">const</span> <span class="token punctuation">{</span><span class="token literal-property property">height</span><span class="token operator">:</span>containerHeight<span class="token punctuation">}</span> <span class="token operator">=</span> textContainer<span class="token punctuation">.</span><span class="token function">getBoundingClientRect</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
        console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>pHeight<span class="token punctuation">,</span>containerHeight<span class="token punctuation">)</span>
        <span class="token keyword">const</span> <span class="token function-variable function">main</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token operator">=></span><span class="token punctuation">{</span>
            <span class="token keyword">if</span><span class="token punctuation">(</span>pHeight<span class="token operator">></span>containerHeight<span class="token punctuation">)</span><span class="token punctuation">{</span>
                ellipsis<span class="token punctuation">.</span>style<span class="token punctuation">.</span>display <span class="token operator">=</span> <span class="token string">'block'</span>
            <span class="token punctuation">}</span><span class="token keyword">else</span><span class="token punctuation">{</span>
                ellipsis<span class="token punctuation">.</span>style<span class="token punctuation">.</span>display <span class="token operator">=</span> <span class="token string">'none'</span>
            <span class="token punctuation">}</span>
        <span class="token punctuation">}</span>
        <span class="token function">main</span><span class="token punctuation">(</span><span class="token punctuation">)</span>
    </span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>script</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>body</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>html</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="_2-移动端适配解决方案" tabindex="-1"><a class="header-anchor" href="#_2-移动端适配解决方案" aria-hidden="true">#</a> 2.移动端适配解决方案</h2>
<h3 id="rem" tabindex="-1"><a class="header-anchor" href="#rem" aria-hidden="true">#</a> rem</h3>
<p>rem是一个相对于页面根元素html的font-size的一个单位，举个例子，假如设置了根元素html的<code v-pre>font-size</code>为<code v-pre>12px</code>，那么，<code v-pre>1rem</code> 等于<code v-pre> 12px</code>。也就是说，rem的大小是会随着根元素html的<code v-pre>font-size</code>的改变而改变的。rem方案就是利用了这一点，根据不同的屏幕尺寸，来设置不同的根元素html的<code v-pre>font-size</code>的大小，以此来达到适配不同屏幕尺寸的目的。</p>
<p>例如：<code v-pre>750px</code>设计稿，如果设置某个div大小为<code v-pre>80px</code>大小，那转化为rem是多少呢？在将设备宽度分为10等分的情况下，<code v-pre>750/10 = 75</code>，<code v-pre>80/75=1.07rem</code>,开发中不可能每个大小有我们自己计算，因此需要使用插件自动帮我们做转换</p>
<p>推荐插件<code v-pre>postcss-pxtorem</code>,使用方式如下，在postcss的插件中进行配置，也可以<code v-pre>postcss.config.js</code>中导出配置。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code>module<span class="token punctuation">.</span>exports <span class="token operator">=</span> <span class="token punctuation">{</span>
    <span class="token string-property property">"plugins"</span><span class="token operator">:</span><span class="token punctuation">{</span>
        <span class="token string-property property">"postcss-pxtorem"</span><span class="token operator">:</span><span class="token punctuation">{</span>
            <span class="token function">rootValue</span><span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span>file<span class="token punctuation">}</span></span><span class="token punctuation">)</span><span class="token punctuation">{</span>
                <span class="token comment">//rootValue可以是number可以是个函数，由于vant基于375设计稿，如果我们使用750设计稿，那尺寸大了一半，因此是vant的时候需要将rootValue设置一般</span>
				<span class="token keyword">return</span> file<span class="token punctuation">.</span><span class="token function">indexOf</span><span class="token punctuation">(</span><span class="token string">'vant'</span><span class="token punctuation">)</span><span class="token operator">!==</span> <span class="token operator">-</span><span class="token number">1</span> <span class="token operator">?</span> <span class="token number">37.5</span> <span class="token operator">:</span> <span class="token number">75</span><span class="token comment">// 这里根据设计图尺寸</span>
            <span class="token punctuation">}</span><span class="token punctuation">,</span> 
            <span class="token literal-property property">proList</span><span class="token operator">:</span><span class="token punctuation">[</span><span class="token string">'*'</span><span class="token punctuation">]</span><span class="token comment">//需要被转换的属性</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="viewport" tabindex="-1"><a class="header-anchor" href="#viewport" aria-hidden="true">#</a> viewport</h3>
<p>viewport是指视窗、视口，即浏览器用来显示网页的那部分区域。在移动端开发中，我们希望页面宽度和设备宽度一致，并把这个viewport称为ideal viewport（理想视口）。我们设置会在html文件中添加<code v-pre>viewport</code>元数据标签，就是为了得到一个我们需要的viewport。</p>
<div class="language-html line-numbers-mode" data-ext="html"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>meta</span> <span class="token attr-name">name</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>viewport<span class="token punctuation">"</span></span> <span class="token attr-name">content</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><ul>
<li><code v-pre>name=&quot;viewport&quot;</code>指定网页在移动端设备上的视口设置。（表述该元数据的作用，允许开发者控制移动设备上网页的显示方式，包括宽度、缩放级别和用户缩放行为，以适应不同的设备屏幕和提供更好的移动浏览体验。）</li>
<li><code v-pre>width=device-width</code>:视口的宽度将与设备的宽度相匹配，确保网页内容能够适应设备屏幕的宽度。</li>
<li><code v-pre>initial-scale=1</code>:使用 <code v-pre>initial-scale</code> 属性可以设置初始的缩放级别，将页面以原始大小显示,即不进行缩放。</li>
<li><code v-pre>maximum-scale=1</code>: 表示用户无法通过手势进行放大操作，将禁用缩放。</li>
<li><code v-pre>minimum-scale=1</code>: 表示用户无法通过手势进行缩小操作，将禁用缩放。</li>
<li><code v-pre>user-scalable=no</code>: 表示用户无法通过手势进行放大缩小操作，将禁用缩放。</li>
</ul>
<p>viewport方案即是使用vw/vh作为样式单位。vw、vh将viewport分成了一百等份，1vw等于视口1%的宽度，1vh等于视口1%的高度。当我们的设计稿是750px时，1vw就等于7.5px。还是用之前那个例子，750px设计稿下，divA的宽度为50px，使用vw作为样式单位，divA的宽度是多少vw呢？还是将divA的宽度设置x vw，代入x:50 = 1:7.5，得到x≈6.67vw。 可以感受到，自行计算的过程相当影响开发进度。所以我们引入了postcss-px-to-viewport插件。</p>
<p>作者：T_macOne
链接：https://juejin.cn/post/7277875605538226195
来源：稀土掘金
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。</p>
<CommentService/></div></template>


